FROM docker.io/imachug/kyzylborda_lib
WORKDIR /task
RUN apk add --no-cache gcc musl-dev
COPY requirements.txt requirements.txt 
RUN pip3 install -r requirements.txt
ENTRYPOINT ["kyzylborda-generate", "generator"]
