category: ctb
points: 250
title: Встроенный Принц
author: udn_t
description: |
  <p>Вас попросили разработать новый интерфейс для дверей Замка Всех
  Принцесс. Однако, у них нет тестового стенда, поэтому ваш код будет
  запускаться на самом настоящем замке! К счастью, их разработчики учли
  этот момент и процессор ЗВП поддерживает режим недоверия, в котором двери
  замка никогда не откроются.</p>

  <p>Разумеется, у вашего сердца свои цели и оно всеми силами хочет открыть
  двери замка. Слушайте свое сердце, оно не обманет.
attachments_path: attachments
generator: [../_scripts/kyzylborda-lib-generator]
daemon:
  exec: kyzylborda-docker-compose-daemon
  cwd: app
  socket: ./app.sock
  socket_type: "http"
  hostnames:
   - princelua.s.2025.ugractf.ru
   - princelua.board.ugractf.ru
