import hashlib
import os
import bencodepy

from kyzylborda_lib.generator import get_attachments_dir
from kyzylborda_lib.secrets import get_flag

with open('story.txt', 'r') as story:
    story = story.read()


def generate():
    flag = story.replace("{flag}", get_flag())

    piece_len = 5

    hash_list = []
    for i in range(0, len(flag), piece_len):
        h = hashlib.sha1()
        h.update(flag[i:i + piece_len].encode("utf-8"))
        hash_list.extend(h.digest())

    flag_enc = bencodepy.encode({
        'announce': 'http://ucucugtracker.local:1337/announce',
        'comment': 'File generated by UcucugTracker v3.7',
        'created by': 'BitTorrent/761337',
        'creation date': 1147350960,
        'info':
            {
                'length': len(flag),
                'name': 'У. Ц. Уцуг - Коллекционер флагов - 2001.txt',
                'piece length': piece_len,
                'pieces': bytes(hash_list)
            }
    })

    with open(os.path.join(get_attachments_dir(), "flags.torrent"), "wb+") as f:
        f.write(flag_enc)
